const script = `--
-- Arquivo gerado com SQLiteStudio v3.4.1 em sex dez 30 20:53:53 2022
--
-- Codificação de texto usada: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Tabela: ADDRESS
DROP TABLE IF EXISTS ADDRESS;

CREATE TABLE IF NOT EXISTS ADDRESS (
    ID         INTEGER PRIMARY KEY AUTOINCREMENT
                       NOT NULL
                       UNIQUE,
    CEP        TEXT    NOT NULL,
    STREET     TEXT    NOT NULL,
    DISTRICT   TEXT    NOT NULL,
    CITY       TEXT    NOT NULL,
    STATE      TEXT    NOT NULL,
    NUMBER     TEXT    NOT NULL,
    COMPLEMENT TEXT,
    CPF_CNPJ   TEXT    REFERENCES CLIENT (CPF_CNPJ) 
                       NOT NULL
);


-- Tabela: CLIENT
DROP TABLE IF EXISTS CLIENT;

CREATE TABLE IF NOT EXISTS CLIENT (
    CPF_CNPJ TEXT PRIMARY KEY
                  NOT NULL
                  UNIQUE,
    NAME     TEXT NOT NULL
);


-- Tabela: CONTACT
DROP TABLE IF EXISTS CONTACT;

CREATE TABLE IF NOT EXISTS CONTACT (
    ID       INTEGER PRIMARY KEY AUTOINCREMENT
                     NOT NULL
                     UNIQUE,
    TYPE     TEXT    NOT NULL,
    CONTACT  TEXT    NOT NULL,
    CPF_CNPJ TEXT    REFERENCES CLIENT (CPF_CNPJ) 
                     NOT NULL
);


-- Tabela: PRODUCT
DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE IF NOT EXISTS PRODUCT (
    ID          INTEGER PRIMARY KEY AUTOINCREMENT
                        UNIQUE
                        NOT NULL,
    NAME        TEXT    NOT NULL,
    PRICE       NUMERIC NOT NULL,
    DESCRIPTION TEXT
);


-- Tabela: PURCHASE
DROP TABLE IF EXISTS PURCHASE;

CREATE TABLE IF NOT EXISTS PURCHASE (
    ID       INTEGER PRIMARY KEY AUTOINCREMENT
                     NOT NULL
                     UNIQUE,
    CPF_CNPJ TEXT    REFERENCES CLIENT (CPF_CNPJ) 
                     NOT NULL,
    DATE     TEXT    NOT NULL
);


-- Tabela: PURCHASE_LIST
DROP TABLE IF EXISTS PURCHASE_LIST;

CREATE TABLE IF NOT EXISTS PURCHASE_LIST (
    ID_PURCHASE INTEGER REFERENCES PURCHASE (ID) 
                        NOT NULL,
    ID_PRODUCT  INTEGER REFERENCES PRODUCT (ID) 
                        NOT NULL,
    AMOUNT      INTEGER NOT NULL
);


-- Tabela: REQUIRE_LIST
DROP TABLE IF EXISTS REQUIRE_LIST;

CREATE TABLE IF NOT EXISTS REQUIRE_LIST (
    ID_SERVICE INTEGER REFERENCES SERVICE (ID) 
                       NOT NULL,
    ID_PRODUCT INTEGER REFERENCES PRODUCT (ID) 
                       NOT NULL,
    AMOUNT     INTEGER NOT NULL
);


-- Tabela: SERVICE
DROP TABLE IF EXISTS SERVICE;

CREATE TABLE IF NOT EXISTS SERVICE (
    ID       INTEGER PRIMARY KEY AUTOINCREMENT
                     UNIQUE
                     NOT NULL,
    ID_PLATE TEXT    REFERENCES VEHICLE (ID_PLATE) 
                     NOT NULL,
    CPF_CNPJ TEXT    REFERENCES CLIENT (CPF_CNPJ) 
                     NOT NULL,
    DATE     TEXT    NOT NULL,
    SERVICE  TEXT    NOT NULL,
    PRICE    NUMERIC NOT NULL
);


-- Tabela: VEHICLE
DROP TABLE IF EXISTS VEHICLE;

CREATE TABLE IF NOT EXISTS VEHICLE (
    ID_PLATE TEXT    PRIMARY KEY
                     UNIQUE
                     NOT NULL,
    BRAND    TEXT    NOT NULL,
    MODEL    TEXT    NOT NULL,
    COLOR    TEXT    NOT NULL,
    YEAR     INTEGER NOT NULL,
    KM       NUMERIC NOT NULL,
    CPF_CNPJ TEXT    REFERENCES CLIENT (CPF_CNPJ) 
                     NOT NULL
);


COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
`
export default script;